version: "3.9"
services:
  dynamodb-local:
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    user: root
    working_dir: /home/dynamodblocal
#    backend:
#      container_name: backend
#      build:
#        context: ./backend
#      image: amirmarmor/seawise_backend
#      privileged: true
#      environment:
#        - HOST=redis
#      devices:
#        - /dev:/dev
#      volumes:
#        - /videos:/app/videos
#      ports:
#        - "1323:1323"
#        - "8080:8080"
#      depends_on:
#        - redis
